### ISSUE TITLE
FOSS License?

### ISSUE THREAD

**Issue by danieljennings** [USA-RedDragon/python-google-sdm#2]
Hi Jacob, I wanted to take a look at this package but I noticed your license file is empty. Is this software FOSS, and if so, would you mind providing (or specifying) a license?

Thanks!

**Comment by USA-RedDragon** [comment]
My mistake. I'll update this shortly. It's going to be licensed under GNU GPL v2.

**Comment by danieljennings** [comment]
Thank you!
